
version: "3.9"
services:
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - api
    restart: unless-stopped
